version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    ignore:
      - dependency-name: "husky"
        versions: ["6.x"]
    open-pull-requests-limit: 5
    versioning-strategy: increase
